version: '3.9'

services:
  db:
    image: postgres:17
    restart: always
    shm_size: '2gb'
    
    environment:
      POSTGRES_USER: <username>
      POSTGRES_PASSWORD: <password>
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data